<?php
/**
 * emdatra — configuration template.
 *
 * Do NOT edit this file with real values. The web installer (install.php)
 * will create the real `config.php` for you from the details you enter.
 *
 * `config.php` is kept ONLY on the server: it is in .gitignore and excluded
 * from auto-deploy, so your database password never reaches GitHub and is
 * never overwritten by a deployment.
 */
return [
    'db' => [
        'host'    => 'localhost',
        'name'    => 'YOUR_DB_NAME',
        'user'    => 'YOUR_DB_USER',
        'pass'    => 'YOUR_DB_PASSWORD',
        'charset' => 'utf8mb4',
    ],
    'site' => [
        'base_url' => 'https://emdatra.emdatra.org',
        'default_lang' => 'ar', // ar | en
    ],
];
